export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERRORS = 'REGISTER_ERRORS';

export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
