export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERRORS = 'REGISTER_ERRORS';

export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERRORS = 'LOGIN_ERRORS';

export const LOGOUT_USER = 'LOGOUT_USER';
